# Site settings
title: בחירות 2015
email: info@no2bio.org
description: "עמדת המפלגות ביחס למאגר הביומטרי, בחירות 2015"
baseurl: "/elections2015/" # the subpath of your site, e.g. /blog/
url: "http://no2bioeditor.github.io" # the base hostname & protocol for your site
fbId: "851200511567882"

# Build settings
markdown: kramdown

collections:
  parties:
    output: true
